### ISSUE TITLE
Error log with HA 2024.2

### ISSUE THREAD

**Issue by mamrai1** [mairas/hysen#59]
Hysen_Climate_Device'>) implements HVACMode(s): auto, heat, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/mairas/hysen/issues

**Comment by Joao-Sousa-71** [comment]
Same here:
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 15:56:34 (33 occurrences)
Last logged: 15:56:34

Entity climate.escritorio_piso0_thermostat9 (<class 'custom_components.hysen.climate.HASS_Hysen_Climate_Device'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/mairas/hysen/issues
Entity climate.escritorio_piso0_thermostat9 (<class 'custom_components.hysen.climate.HASS_Hysen_Climate_Device'>) implements HVACMode(s): auto, heat, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/mairas/hysen/issues

**Comment by mcc05** [comment]
Really sorry but I can't support this I done have one of the thermostats anymore.

**Comment by eifinger** [comment]
Have you tried the core integration? Support for Broadlink Thermostats was added a while ago https://www.home-assistant.io/integrations/broadlink/#climate

**Comment by Joao-Sousa-71** [comment]
@eifinger that deserves a try. If the programming features are available I probably change it.

**Comment by Joao-Sousa-71** [comment]
@mcc05 after some research I found the solution. This is a change in HA with the deprecation version 2025.1

[New entity features in Climate entity](https://developers.home-assistant.io/blog/2024/01/24/climate-climateentityfeatures-expanded/)

The fix is pretty straight:
in the climate.py file, on the line 69 replace:

`SUPPORT_FEATURES = ClimateEntityFeature.PRESET_MODE | ClimateEntityFeature.TARGET_TEMPERATURE`

by:

`SUPPORT_FEATURES = ClimateEntityFeature.PRESET_MODE | ClimateEntityFeature.TARGET_TEMPERATURE | ClimateEntityFeature.TURN_OFF | ClimateEntityFeature.TURN_ON`

in the line 558 add the following:

`        self._enable_turn_on_off_backwards_compatibility = False`

and Profit.

@mamrai1 please try it!

**Comment by mamrai1** [comment]
thank you! it works
@mcc05 I have made a pull request
